---
- name: Установка стандартных пакетов
  hosts: all
  become: yes
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка nginx для проксирования
  hosts: proxy
  become: yes
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Установка и настройка nginx c кастомной страницей
  hosts: nginx
  become: yes
  roles:
    - role: nginx_custom
  tags:
    - nginx_custom

